#!/usr/bin/bash
export BW_SESSION=`bw unlock --raw`
if [[ $BW_SESSION ]]; then
  bwdata=`bw list items`;
  if [[ $bwdata ]]; then
    echo $bwdata\
      | jq '.[] | .name + " (" + .login.username + ") -- ID: " + .id'\
      | sed 's/\"//g'\
      | fzf -i\
        --bind "enter:execute(bw get password {-1} | wl-copy)"
  fi
fi
