# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

from os import environ

config.load_autoconfig()


config.set('content.notifications', False, '*')
c.content.autoplay = False
c.content.mute = True
c.content.pdfjs = True

c.downloads.location.directory = environ.get('HOME') + '/Downloads'
c.downloads.position = 'bottom'

c.editor.command = ['alacritty', '-e', 'nvim', '{file}']

c.input.insert_mode.auto_load = True

c.qt.force_platformtheme = 'qt5ct'
c.qt.highdpi = True

c.spellcheck.languages = ['en-US']

c.statusbar.padding = {'bottom': 2, 'left': 6, 'right': 6, 'top': 2}

c.tabs.favicons.scale = 1.0
c.tabs.favicons.show = 'always'
c.tabs.indicator.width = 6
c.tabs.indicator.padding = {'bottom': 2, 'left': 0, 'right': 4, 'top': 2}
c.tabs.last_close = 'close'
c.tabs.mode_on_change = 'normal'
c.tabs.mousewheel_switching = False
c.tabs.new_position.related = 'next'
c.tabs.new_position.unrelated = 'last'
c.tabs.new_position.stacking = True
c.tabs.padding = {'bottom': 6, 'left': 5, 'right': 5, 'top': 4}
c.tabs.position = 'top'

c.window.hide_decoration = True
c.window.title_format = '{perc}{current_title}{title_sep}qutebrowser'

c.zoom.default = '100%'
c.zoom.levels = ['50%', '67%', '75%', '100%', '125%', '150%', '175%', '200%']
